name: Build and Push Docker Images

on:
  push:
    branches: [ dattk ]

jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image (native arch)
        run: |
          docker build \
          --no-cache \
          --build-arg NEXT_PUBLIC_TURNSTILE_SITE_KEY=0x4AAAAAABLfdqrrH9bmKIai \
          --build-arg NEXT_PUBLIC_SITE_URL=https://dattk.com \
          --build-arg NEXT_PUBLIC_IMAGE_HOST=https://image.moly.onl \          
          -t ${{ secrets.DOCKER_USERNAME }}/moly:${{ github.ref_name }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/moly:${{ github.ref_name }}
